### ISSUE TITLE
Rename supertux-history.md to releases.md?

### ISSUE THREAD

**Issue by provigz** [supertux-community/supertux-history#1]
What do you think of the idea for renaming the `supertux-history.md` file to `releases.md` or some other name, that will represent release dates being stored there? The reason I'm asking this is because it currently mainly contains release dates of versions and other information is already being stored in different files.

**Comment by mrkubax10** [comment]
What about team members join dates?

**Comment by provigz** [comment]
You mean like a different file? Sounds good.

**Comment by mrkubax10** [comment]
Then I think it can be renamed

**Comment by provigz** [comment]
Sounds good to me. :)
